############################
## CHANGE THESE
############################

baseURL: 'https://thareeqroshan.github.io/personal_portfolio'
title: personal_portfolio

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


