############################
## CHANGE THESE
############################

baseURL: "https://thareeqroshan.github.io/"
title: "Thareeq Roshan - Sound Designer"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
